In [10]:
df_1 = _dntk.execute_sql(
  'SELECT *\nFROM \'retail_sales.csv\'\nLIMIT 10;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_1

,OrderID,Product,Category,UnitsSold,UnitPrice,Revenue,Date,Region
0,1001,Mouse,Electronics,9,25,225,2023-05-26,East
1,1002,Monitor,Electronics,3,200,600,2023-08-10,East
2,1003,Water Bottle,Accessories,4,10,40,2023-07-15,South
3,1004,Monitor,Electronics,1,200,200,2023-07-07,North
4,1005,Monitor,Electronics,1,200,200,2023-04-13,East
5,1006,Desk,Furniture,7,300,2100,2023-06-10,East
6,1007,Notebook,Stationery,1,3,3,2023-02-13,North
7,1008,Water Bottle,Accessories,2,10,20,2023-10-30,West
8,1009,Pen,Stationery,3,1,3,2023-05-27,North
9,1010,Water Bottle,Accessories,6,10,60,2023-03-13,North

In [16]:
Total_Revenue = _dntk.execute_sql(
  'SELECT SUM(Revenue) AS total_revenue\nFROM "retail_sales.csv";',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Total_Revenue

   total_revenue
0       186829.0

In [22]:
Top_5_Best_Selling_Products = _dntk.execute_sql(
  'SELECT Product, SUM(UnitsSold) AS total_units\nFROM "retail_sales.csv"\nGROUP BY Product\nORDER BY total_units DESC\nLIMIT 5;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Top_5_Best_Selling_Products

        Product  total_units
0      Backpack        159.0
1         Mouse        148.0
2        Laptop        139.0
3          Desk        110.0
4  Water Bottle         99.0

In [25]:
Revenue_by_Region = _dntk.execute_sql(
  'SELECT Region, SUM(Revenue) AS region_revenue\nFROM "retail_sales.csv"\nGROUP BY Region\nORDER BY region_revenue DESC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Revenue_by_Region

  Region  region_revenue
0   West         54253.0
1  South         52962.0
2   East         50666.0
3  North         28948.0

In [55]:
Revenue_by_product_category = _dntk.execute_sql(
  'SELECT Category, SUM(Revenue) AS category_revenue\nFROM "retail_sales.csv"\nGROUP BY Category\nORDER BY category_revenue DESC;',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Revenue_by_product_category

      Category  category_revenue
0  Electronics          131860.0
1    Furniture           47400.0
2  Accessories            7350.0
3   Stationery             219.0

In [31]:
Average_Order_Value = _dntk.execute_sql(
  'SELECT AVG(Revenue) AS avg_order_value\nFROM "retail_sales.csv";',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
Average_Order_Value

   avg_order_value
0          934.145

# 📈 Retail Sales SQL Analysis

This project analyzes retail sales data using SQL to answer key business questions.

 Key Questions Answered
- Which products sell the most?
- How much revenue does each region generate?
- Which category generates the most revenue?
- What's the average value of an order?

 Summary of Insights
- Total revenue: $186829
- Best-selling product: Backpack
- Region with highest sales: East
- Category with highest revenue: Electronics
- Average order value: $934.145

 Dataset
Simulated retail sales data with fields: OrderID, Product, Category, UnitsSold, UnitPrice, Revenue, Date, Region

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=1f9b6c48-14bd-4856-add1-d15eebe081d5' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>